# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - 'releases/**'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

jobs:
  node:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Install Workspaces dependencies
        run: bash ./scripts/deps.sh
      - name: Run standard tests
        run: npm test --if-present
      - name: Run redaction tests
        run: bash ./scripts/testing.sh
  browser:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 16.x ]
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - run: npm run test:browser
  coverage:
    runs-on: ${{ matrix.os }}
    needs:
      - node
      - browser

    strategy:
      matrix:
        node-version: [ 16.x ]
        os: [ ubuntu-latest, macos-latest ]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS, NODE
          fail_ci_if_error: true
